name: Lottery
main: com.mengcraft.lottery.Main
version: 0.1.1

commands:
  cj:
    description: Default command for this plug-in.
    permission: lottery.use
    
permissions:
  lottery.use:
    description: Default permission for this plug-in.
    default: op
  lottery.admin:
    description: Operator permission for this plug-in.
    default: op

depend: [ProtocolLib]